ya-in-f26.1e100.net,:on: [push]

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.1.4
